name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the base environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Step to pull the latest code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install pytest  # Install pytest
          pip install -r requirements.txt  # Install other dependencies from requirements.txt (if you have one)

      - name: Run tests with pytest
        run: pytest  # Run pytest after dependencies are installed
